FROM ubuntu:22.04

RUN apt update \
  && apt-get install -y curl \
  && curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh \
  && bash nodesource_setup.sh \
  && apt-get install -y nodejs

WORKDIR /app

COPY index.mjs ./

EXPOSE 3000

CMD ["node", "index.mjs"]
